ENVANTERYONETIMI/Controllers/ProductController.cs
using ENVANTERYONETIMI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;

namespace ENVANTERYONETIMI.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDBContext _context;
        

        public ProductController(ApplicationDBContext context)
        {
            _context = context;
            

        }

        // GET: Product/Index
        public async Task<IActionResult> Index()
        {
            var products = await _context.Products.Include(p => p.ProductSubcategory).ToListAsync();
            return View(products);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            if (ModelState.IsValid)
            {
               
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
           
            return View(product);
        }

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductID,ProductName,SubcategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued")] Product product)
        {
            if (id != product.ProductID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductID == id);
        }
    }
}

ENVANTERYONETIMI/Controllers/ProductDetailController.cs
using ENVANTERYONETIMI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace ENVANTERYONETIMI.Controllers
{
    public class ProductDetailController : Controller
    {
        private readonly ApplicationDBContext _context;

        public ProductDetailController(ApplicationDBContext context)
        {
            _context = context;
        }

        // GET: /ProductDetail/
        public async Task<IActionResult> Index()
        {
            var products = await (from p in _context.Products
                                  join pc in _context.ProductCategories on p.CategoryID equals pc.CategoryID
                                  join pi in _context.ProductInventories on p.ProductID equals pi.ProductID
                                  join ps in _context.ProductSubcategories on p.SubcategoryID equals ps.SubcategoryID
                                  select new ProductDetail
                                  {
                                      ProductID = p.ProductID,
                                      CategoryID = p.CategoryID,
                                      InventoryID = pi.InventoryID,
                                      SubcategoryID = p.SubcategoryID,
                                      ProductName = p.ProductName,
                                      SafetyStockLevel = p.SafetyStockLevel,
                                      StandardCost = p.StandardCost,
                                      ListPrice = p.ListPrice,
                                      CategoryName = pc.CategoryName,
                                      Quantity = pi.Quantity,
                                      Shelf = pi.Shelf,
                                      Bin = pi.Bin,
                                      SubcategoryName = ps.SubcategoryName,
                                      ImageUrl = p.ImageUrl
                                  }).ToListAsync();

            // Get distinct categories for the dropdown
            var distinctCategories = await _context.ProductCategories
                                                   .Select(pc => pc.CategoryName)
                                                   .Distinct()
                                                   .ToListAsync();

            ViewBag.DistinctCategories = distinctCategories;

            return View(products);
        }

        // GET: /ProductDetail/FilterByCategory
        

        // POST: /ProductDetail/GetTable
        [HttpPost]
        public async Task<IActionResult> GetTable(List<string> selectedColumns)
        {
            // Debugging için seçilen kolonları kontrol et
            System.Diagnostics.Debug.WriteLine("Seçilen kolonlar: " + string.Join(", ", selectedColumns));

            var products = await (from p in _context.Products
                                  join pc in _context.ProductCategories on p.CategoryID equals pc.CategoryID
                                  join pi in _context.ProductInventories on p.ProductID equals pi.ProductID
                                  join ps in _context.ProductSubcategories on p.SubcategoryID equals ps.SubcategoryID
                                  select new ProductDetail
                                  {
                                      ProductID = p.ProductID,
                                      CategoryID = p.CategoryID,
                                      InventoryID = pi.InventoryID,
                                      SubcategoryID = p.SubcategoryID,
                                      ProductName = p.ProductName,
                                      SafetyStockLevel = p.SafetyStockLevel,
                                      StandardCost = p.StandardCost,
                                      ListPrice = p.ListPrice,
                                      CategoryName = pc.CategoryName,
                                      Quantity = pi.Quantity,
                                      Shelf = pi.Shelf,
                                      Bin = pi.Bin,
                                      SubcategoryName = ps.SubcategoryName,
                                      ImageUrl = p.ImageUrl
                                  }).ToListAsync();

            var dataTable = ConvertToDataTable(products);
            var filteredTable = FilterDataTable(dataTable, selectedColumns);

            var htmlTable = GenerateHtmlTable(filteredTable);
            return Content(htmlTable, "text/html");
        }

        private DataTable ConvertToDataTable(List<ProductDetail> list)
        {
            var dataTable = new DataTable();

            // Dynamically add columns based on the properties of InventoryViewModel
            dataTable.Columns.Add("ProductID");
            dataTable.Columns.Add("CategoryID");
            dataTable.Columns.Add("InventoryID");
            dataTable.Columns.Add("SubcategoryID");
            dataTable.Columns.Add("ProductName");
            dataTable.Columns.Add("SafetyStockLevel");
            dataTable.Columns.Add("StandardCost");
            dataTable.Columns.Add("ListPrice");
            dataTable.Columns.Add("CategoryName");
            dataTable.Columns.Add("Quantity");
            dataTable.Columns.Add("Shelf");
            dataTable.Columns.Add("Bin");
            dataTable.Columns.Add("SubcategoryName");
            dataTable.Columns.Add("ImageUrl");

            foreach (var item in list)
            {
                var row = dataTable.NewRow();
                row["ProductID"] = item.ProductID;
                row["CategoryID"] = item.CategoryID;
                row["InventoryID"] = item.InventoryID;
                row["SubcategoryID"] = item.SubcategoryID;
                row["ProductName"] = item.ProductName;
                row["SafetyStockLevel"] = item.SafetyStockLevel;
                row["StandardCost"] = item.StandardCost;
                row["ListPrice"] = item.ListPrice;
                row["CategoryName"] = item.CategoryName;
                row["Quantity"] = item.Quantity;
                row["Shelf"] = item.Shelf;
                row["Bin"] = item.Bin;
                row["SubcategoryName"] = item.SubcategoryName;
                row["ImageUrl"] = item.ImageUrl;

                dataTable.Rows.Add(row);
            }

            return dataTable;
        }

        private DataTable FilterDataTable(DataTable dataTable, List<string> selectedColumns)
        {
            var filteredTable = dataTable.DefaultView.ToTable(false, selectedColumns.ToArray());
            return filteredTable;
        }

        private string GenerateHtmlTable(DataTable dataTable)
        {
            var html = "<table class='table table-striped'><thead><tr>";

            // Header
            foreach (DataColumn column in dataTable.Columns)
            {
                html += $"<th>{column.ColumnName}</th>";
            }
            html += "</tr></thead><tbody>";

            // Rows
            foreach (DataRow row in dataTable.Rows)
            {
                html += "<tr>";
                foreach (DataColumn column in dataTable.Columns)
                {
                    html += $"<td>{row[column]}</td>";
                }
                html += "</tr>";
            }
            html += "</tbody></table>";

            return html;
        }
    }
}

ENVANTERYONETIMI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ENVANTERYONETIMI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ENVANTERYONETIMI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">

</head>
<body >
    <div class="container-fluid">
        <div class="row ">
            <div class="col-2 sidebar">
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
                    <div class="container-fluid flex-column">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inventory<br/>Management</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse  flex-column ">
                            <ul class="navbar-nav w-100">
                                <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home" style="margin-right: 15px;font-size:25px;"></i>Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="InventoryViewModel" asp-action="Index"><i class="fa-solid fa-warehouse" style="margin-right: 15px;font-size:25px;"></i>Products List</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="Product" asp-action="Index"><i class="fa-solid fa-archive" style="margin-right: 15px;font-size:25px;"></i>Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="ProductDetail" asp-action="Index"><i class="fa fa-th-list" style="margin-right: 15px;font-size:25px;"></i>Product Detail</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
           </div>
            <div class="col-10 main">
                <div class="contrainer">
                    <div class="row">
                        <main role="main" class="pb-3">
                            @RenderBody()
                        </main>
                    </div>
                    
                </div>
                
           </div>
       </div>
   </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>